Fix bug #22
A hotfix to fix the issue #22.
A resource was missing and this resource was used to initialize a final
variable.

The missing resource `no_image_available.png`, was causing to throw a
`NoClassDefFoundError` exception, making the instantiation of DataAccess
impossible.